"""add root_cause table

Revision ID: 78369f9dfbeb
Revises: edd0d7357a66
Create Date: 2022-03-23 15:35:18.725628

"""

# revision identifiers, used by Alembic.
revision = '78369f9dfbeb'
down_revision = 'edd0d7357a66'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bug', sa.Column('root_cause_id', sa.Integer(), nullable=False))
    op.alter_column('bug', 'bug_tracker_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_bug_root_cause_id'), 'bug', ['root_cause_id'], unique=False)
    op.create_unique_constraint(None, 'bug', ['bug_tracker_url'])
    op.create_foreign_key(None, 'bug', 'root_cause', ['root_cause_id'], ['id'])
    op.drop_column('bug', 'root_cause')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug', sa.Column('root_cause', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bug', type_='foreignkey')
    op.drop_constraint(None, 'bug', type_='unique')
    op.drop_index(op.f('ix_bug_root_cause_id'), table_name='bug')
    op.alter_column('bug', 'bug_tracker_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bug', 'root_cause_id')
    op.drop_table('root_cause')
    ### end Alembic commands ###
